# Generated by Django 4.0.3 on 2022-04-06 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Logistic', 'Logistic'), ('Programing', 'Programing'), ('Interesting', 'Interesting')], default='Interesting', max_length=12)),
                ('language', models.CharField(choices=[('Uzbek', 'Uzbek'), ('Russian', 'Russian'), ('English', 'English')], default='Uzbek', max_length=8)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('video_url', models.URLField(max_length=500)),
                ('add_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
